# Azure OpenAI Credentials for Streamlit Cloud
# IMPORTANT: Add these secrets in Streamlit Cloud dashboard, NOT in this file
# Go to: App Settings > Secrets tab
# Paste your credentials there - they will NOT be stored in git

# Example format (DO NOT commit actual values):
# AZURE_OPENAI_API_KEY = "your_secret_key"
# AZURE_OPENAI_ENDPOINT = "https://agenticdevelopment-aoai.openai.azure.com"
# OPENAI_API_VERSION = "2025-01-01-preview"
# OPENAI_MODEL = "gpt-4.1"
